### ISSUE TITLE
implement splunk index backup/restore

### ISSUE THREAD

**Issue by tribaljack** [quintilesims/Splunk#3]
likely, or if the indexes get too big, we can think about using EFS or EBS.
## option S3 Backup
we can use https://github.com/andycmaj/docker-backup to schedule periodic index backups, then when re-creating slaves, do a restore from S3
need to backup only our hec index, so maybe keep that in a separate path
this docker-backup thing has no restore feature. we'd need to add that
## option EFS
If EFS, we'd need to create a new index to use for all our http-event-collector events, and store this on the mounted EFS volume.... This might not make sense since indexes are replicated.
would we write indexes on ALL replicated slaves to the same EFS mount, but in different root paths? that might work, but might cancel out any perf gains that come from clustered indexing...
maybe have one EFS volume per slave?
## option EBS
mount EBS volumes on each instance, create docker task to take snapshots of ONE of the replicated indexes, and whenever we need to re-create an environment, we'd have to modify the userdata.sh used to create the environment to load all EBS volumes from the snapshot.
would this work with index replication? if all new slaves/new master have same restored EBS volume, this might break splunk index replication?

**Comment by sesh-kebab** [comment]
Done - using a persistent storage deployment.
